"""Generate PAPERS.md — a flat, deduplicated index of every cited paper
across the programmes and essays.

The index is *generated*, not edited by hand. To add or remove a paper from
the index, edit the corresponding programme/essay file and re-run this script.

Usage:
    python scripts/generate_papers_index.py [--out PAPERS.md]

Format of each row:
    | arXiv ID | Year | Title | Programme(s) | Cited in |

We resolve titles by re-using the .cache/arxiv-verify.json built by
scripts/verify_citations.py (so we do not re-query the arXiv API).
"""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path

CACHE_PATH = Path(".cache/arxiv-verify.json")
ARXIV_LINK_RE = re.compile(r"https?://arxiv\.org/abs/(?P<id>[0-9]{4}\.[0-9]{4,5})")
SCAN_ROOTS = [
    Path("programmes"),
    Path("essays"),
    Path("reading-paths"),
    Path("README.md"),
    Path("GLOSSARY.md"),
    Path("FAQ.md"),
    Path("TOOLS.md"),
    Path("tracker"),
]
PROGRAMME_FILES = {
    "01": Path("programmes/01-compression-as-intelligence.md"),
    "02": Path("programmes/02-superposition-linear-rep.md"),
    "03": Path("programmes/03-circuits-and-biology.md"),
    "04": Path("programmes/04-icl-as-bayes-meta-learning.md"),
    "05": Path("programmes/05-emergence-and-reasoning.md"),
    "adj": Path("programmes/adjacent-programmes.md"),
}


def md_files(roots):
    for r in roots:
        if r.is_dir():
            yield from r.rglob("*.md")
        elif r.exists():
            yield r


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default="PAPERS.md")
    args = ap.parse_args()

    cache = {}
    if CACHE_PATH.exists():
        try:
            cache = json.loads(CACHE_PATH.read_text(encoding="utf-8"))
        except Exception:
            cache = {}

    # Map: arxiv_id -> set of files in which it appears.
    where: dict[str, set[Path]] = defaultdict(set)
    for f in md_files(SCAN_ROOTS):
        text = f.read_text(encoding="utf-8")
        for m in ARXIV_LINK_RE.finditer(text):
            where[m.group("id")].add(f)

    # Map: arxiv_id -> set of programmes that cite it.
    by_programme: dict[str, set[str]] = defaultdict(set)
    for aid, files in where.items():
        for f in files:
            for pid, p in PROGRAMME_FILES.items():
                try:
                    if f.resolve() == p.resolve():
                        by_programme[aid].add(pid)
                except OSError:
                    pass

    rows = []
    for aid in sorted(where):
        meta = cache.get(aid, {})
        title = (meta.get("title") or "").strip().replace("\n", " ")
        year = meta.get("year") or ""
        progs = ", ".join(sorted(by_programme[aid])) or "—"
        cited_in = ", ".join(sorted({f.as_posix() for f in where[aid]}))
        if not title:
            title = "_(title unresolved; run scripts/verify_citations.py first)_"
        rows.append(
            f"| [arXiv:{aid}](https://arxiv.org/abs/{aid}) | {year} | "
            f"{title} | {progs} | {cited_in} |"
        )

    header = (
        "# Papers index (generated)\n\n"
        "> Auto-generated by `scripts/generate_papers_index.py`. **Do not edit by hand** —\n"
        "> edit the corresponding programme or essay file and re-run the script.\n>\n"
        "> The index is a flat view of every arXiv-cited paper across the repo,\n"
        "> with its programme assignment(s) and the files that cite it. Use the\n"
        "> programme files (or the GLOSSARY / FAQ) for *opinionated* navigation;\n"
        "> use this index when you need to know whether the repo cites a specific\n"
        "> paper.\n\n"
        f"Total unique papers: **{len(rows)}**.\n\n"
        "| arXiv ID | Year | Title | Programme(s) | Cited in |\n"
        "|----------|------|-------|--------------|----------|\n"
    )
    body = "\n".join(rows) + "\n"
    Path(args.out).write_text(header + body, encoding="utf-8")
    print(f"wrote {args.out} ({len(rows)} papers)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
