"""Query arXiv for new papers matching programme-specific search terms and
write a draft pull request body listing the candidates.

This is a *stub* — it queries arXiv and produces a markdown draft of paper-
suggestion entries. It does NOT auto-commit or auto-merge anything.

Usage (CI or local):
    python scripts/ingest_arxiv.py --since 2026-04-01 --out tracker/inbox-2026-05.md

The intended CI flow:
1. Run this script weekly via .github/workflows/arxiv-ingest.yml.
2. It writes the candidates file to a feature branch.
3. CI opens a draft PR with that file. Maintainers triage and either merge
   entries into the appropriate programme files (after adding programme,
   status, annotation, falsifier) or close the PR.
"""

from __future__ import annotations

import argparse
import datetime
import sys
import time
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

ARXIV_SEARCH = (
    "http://export.arxiv.org/api/query?search_query={query}"
    "&start=0&max_results={max_results}"
    "&sortBy=submittedDate&sortOrder=descending"
)

# (programme_id, label, search query). Keep terms specific and avoid noisy keywords.
PROGRAMME_QUERIES = [
    (
        "01",
        "compression-as-intelligence",
        '(abs:"compression" AND abs:"language model") OR abs:"bits-per-byte" OR abs:"compression intelligence"',
    ),
    (
        "02",
        "superposition-LRH",
        '(abs:"superposition" AND abs:"language model") OR abs:"sparse autoencoder" '
        'OR abs:"linear representation hypothesis" OR abs:"dictionary learning" AND abs:"interpretability"',
    ),
    (
        "03",
        "circuits",
        '(abs:"mechanistic interpretability") OR abs:"circuit discovery" OR abs:"induction head" '
        'OR abs:"activation patching" OR abs:"attribution patching"',
    ),
    (
        "04",
        "icl-as-bayes",
        '(abs:"in-context learning" AND (abs:"Bayesian" OR abs:"meta-learning" OR abs:"gradient descent"))',
    ),
    (
        "05",
        "emergence-and-reasoning",
        '(abs:"emergent abilities") OR abs:"test-time compute" OR abs:"chain of thought" '
        'OR abs:"reasoning" AND abs:"reinforcement learning"',
    ),
]


def fetch(query: str, max_results: int = 25) -> list[dict]:
    url = ARXIV_SEARCH.format(query=urllib.parse.quote(query), max_results=max_results)
    with urllib.request.urlopen(url, timeout=30) as resp:
        xml = resp.read().decode("utf-8")
    ns = {"a": "http://www.w3.org/2005/Atom"}
    root = ET.fromstring(xml)
    out = []
    for entry in root.findall("a:entry", ns):
        id_el = entry.find("a:id", ns)
        title_el = entry.find("a:title", ns)
        pub_el = entry.find("a:published", ns)
        summary_el = entry.find("a:summary", ns)
        authors = [
            (a.find("a:name", ns).text or "")
            for a in entry.findall("a:author", ns)
        ]
        out.append(
            {
                "id": id_el.text if id_el is not None else "",
                "title": (title_el.text or "").strip() if title_el is not None else "",
                "authors": authors,
                "published": (pub_el.text or "")[:10] if pub_el is not None else "",
                "summary": (summary_el.text or "").strip()[:300] if summary_el is not None else "",
            }
        )
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--since",
        default=(datetime.date.today() - datetime.timedelta(days=14)).isoformat(),
        help="ISO date; only include arXiv entries published on or after this date.",
    )
    p.add_argument("--max-per-programme", type=int, default=15)
    p.add_argument("--out", default="-", help="output file (- for stdout)")
    args = p.parse_args()

    since = datetime.date.fromisoformat(args.since)
    today = datetime.date.today().isoformat()

    md_lines = [
        f"# Inbox — arXiv ingestion {today}",
        "",
        f"> Generated by `scripts/ingest_arxiv.py` for papers submitted on or after **{since}**.",
        ">",
        "> This is a *triage queue*. Entries below are candidates; each must be triaged into the appropriate programme file with full annotation (programme assignment, claim, status, falsifier) before merging.",
        "",
    ]
    total = 0
    for programme_id, label, query in PROGRAMME_QUERIES:
        md_lines.append(f"## Programme {programme_id} — {label}")
        md_lines.append("")
        try:
            entries = fetch(query, max_results=args.max_per_programme)
        except Exception as e:  # noqa: BLE001
            md_lines.append(f"_query failed: {e}_")
            md_lines.append("")
            continue
        # filter by publication date
        recent = [e for e in entries if e["published"] and e["published"] >= since.isoformat()]
        if not recent:
            md_lines.append("_no new entries in window_")
            md_lines.append("")
            continue
        for e in recent:
            short_id = e["id"].split("abs/")[-1]
            authors_short = ", ".join(e["authors"][:3])
            if len(e["authors"]) > 3:
                authors_short += " et al."
            md_lines.append(
                f"- **{e['title']}** ({e['published'][:4]}) — *{authors_short}*. "
                f"[arXiv:{short_id}]({e['id']})"
            )
            md_lines.append(f"  - **Published**: {e['published']}")
            md_lines.append(f"  - **Programme**: {programme_id}  (proposed; triage)")
            md_lines.append(f"  - **Claim**: (triage; one sentence from actual reading)")
            md_lines.append(f"  - **Status**: ⚪ Open  (proposed; defend on PR)")
            md_lines.append(f"  - **Why it matters**: (triage; max 80 words, from actual reading)")
            md_lines.append(f"  - **Abstract excerpt**: {e['summary']}")
            md_lines.append("")
            total += 1
        time.sleep(1.0)
    md_lines.append(f"_Total candidates: {total}._")

    out_text = "\n".join(md_lines) + "\n"
    if args.out == "-":
        sys.stdout.write(out_text)
    else:
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.out).write_text(out_text, encoding="utf-8")
        print(f"wrote {args.out} ({total} candidates)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
